### ISSUE TITLE
Swift streams is broken again 

### ISSUE THREAD

**Issue by RickFromTexas** [team-crew/team-crew.github.io#1]
I get an error message from The Crew in Kodi, just wanted to let someone know. Thanks!

**Comment by RickFromTexas** [comment]
I hate to bother you but I tried using swift streams this morning and got an error message. Not just in The Crew though, doesn't seem to be working in other addons either. Only difference is I get an error message on The Crew when I click on swift streams, the other addons let me see the links for other countries like Canada but nothing plays.
________________________________

**Comment by eeden003** [comment]
Same here, since a week, but well........it's not completely legal isn't it
?

Op do 26 dec. 2019 19:13 schreef RickFromTexas <notifications@github.com>:

**Comment by thecrewwh** [comment]
I will check it again I used it yesterday and it worked fine

**Comment by thecrewwh** [comment]
Just tested and some channels are up and some aren't but it does work
