### ISSUE TITLE
crew tools navigation Menu. 

### ISSUE THREAD

**Issue by Greg0580** [team-crew/team-crew.github.io#100]
i have been searching for how to set up personal list and personal url  but cant find anything how to set it up .
Crew/Tools/Navigation/Personal/Enable/Personal List URL . but i dont know what to fill in here.  do i put in IMDB, TMDB, Url address/s or something else . any help would be Great Thank You
                                 
                                   Greg.

**Comment by sidouglas** [comment]
Check out https://www.videoconverterfactory.com/kodi/imdb-kodi.html - it's a very similar process. 
TLDR: use your user id  when viewing your watch list.
https://www.imdb.com/user/**ur1XXXXXXXX7**/watchlist

**Comment by thecrewwh** [comment]
personal list when enabled always you to add any url you want to it like your own xml you have or someone elses this is a feature for your use not ours
