### ISSUE TITLE
Video Addon The Crew download not working

### ISSUE THREAD

**Issue by Stivan101** [team-crew/team-crew.github.io#101]
I'm not able to download the The Crew Addon.

**Comment by fade2gray** [comment]
You've followed a relevant guide for installation, such as https://www.wirelesshack.org/how-to-install-the-crew-kodi-addon.html?

**Comment by Stivan101** [comment]
> You've followed a relevant guide for installation, such as https://www.wirelesshack.org/how-to-install-the-crew-kodi-addon.html?

I've already did this but it says Script.module.beautifulsoup4 .0.0.0.0 won't work.

**Comment by fade2gray** [comment]
You'll have to try asking them at `Team-Crew` on [Telegram Messenger](https://telegram.org).
