### ISSUE TITLE
The crew addon settings. 

### ISSUE THREAD

**Issue by Greg0580** [team-crew/team-crew.github.io#102]
How to use  a d setup Personal list.  In Navagation   please.

**Comment by Greg0580** [comment]
Can't find the Crew page on telegram.

**Comment by fade2gray** [comment]
They've changed the group name from `Team-Crew` to `The Crew and Purely Community`.
![telegram](https://user-images.githubusercontent.com/1332009/186883115-9f0ead78-49e7-4f9d-a491-6043b55a8b3a.PNG)

**Comment by Zippy457** [comment]
I'm not able to find the group either. I copied and pasted the name from the previous post.

![image](https://user-images.githubusercontent.com/107886945/186977739-01dc4f3d-3088-487c-b401-e354defee66d.png)

**Comment by fade2gray** [comment]
@Greg0580 @Zippy457 
It's been a while since a joined the group, and procedure has changed since, so it's invitation link only.

You need to use this link (it might expire over time - I don't know for sure). https://t.me/+kpjtZC-e63lhMGNh

**Comment by Greg0580** [comment]
It  works thank you 😊



Sent from my Galaxy



-------- Original message --------
From: fade2gray ***@***.***>
Date: 28/08/22 05:28 (GMT+12:00)
To: "team-crew/team-crew.github.io" ***@***.***>
Cc: Greg0580 ***@***.***>, Mention ***@***.***>
Subject: Re: [team-crew/team-crew.github.io] The crew addon settings. (Issue #102)


@Greg0580<https://github.com/Greg0580> @Zippy457<https://github.com/Zippy457>
It's been a while since a joined the group, and procedure has changed since, so it's invitation link only.

You need to use this link (it might expire over time - I don't know for sure). https://t.me/+kpjtZC-e63lhMGNh

**Comment by dhdeanha** [comment]
> @Greg0580 @Zippy457 It's been a while since a joined the group, and procedure has changed since, so it's invitation link only.
> 
> You need to use this link (it might expire over time - I don't know for sure). https://t.me/+kpjtZC-e63lhMGNh

Link expired

**Comment by Zippy457** [comment]
The link above is expired. Can someone generate another?

**Comment by thecrewwh** [comment]
https://t.me/+NcDJAV6rYM4zNjAx
