### ISSUE TITLE
Homelander Not Available for Install in Kodi 18 Despite it Working Same as Kodi 19

### ISSUE THREAD

**Issue by whatsuprob** [team-crew/team-crew.github.io#103]
Is there anyway that you can unblock Homeland for Kodi 18 Users so we can Install it?  I was shocked when I copy and pasted it over to Kodi 18 and it worked. There are not many elite addons from reliable developer teams on Kodi 18 anymore and this would go a long way to fill the void while everyone scrambles to fix some of the tradeoffs/issues that still come with Kodi 19 in Kodi 20. Mainly the TMDB Helper, Super Favs, and Issues with scripts that help find dead repos and other issues with 1 click.

**Comment by thecrewwh** [comment]
I can add it
