### ISSUE TITLE
Resume playback point not working

### ISSUE THREAD

**Issue by apg31** [team-crew/team-crew.github.io#104]
Resume playback works in 18 .9 but not in 19.4.
No error message though just always starts from beginning.
I also tried using it with Trakt, same thing.
Other addons work fine so I do not think it is anything I have set wrong.
Really prefer to use the crew but wife is bugging me about it as she often
stops shows in the middle and then comes back to them when she gets
a chance. 
Thanks for any help you can give....

I believe this may be the same issue as #95.

**Comment by thecrewwh** [comment]
I will take a look at the resume for 19

**Comment by suzie59** [comment]
My playback doesn't work either

**Comment by Strongheart05** [comment]
Nor does mine
