### ISSUE TITLE
Bitdefender Windows warns: \client.py is infected with Trojan.Generic.31710459

### ISSUE THREAD

**Issue by EvilCaptKirk** [team-crew/team-crew.github.io#106]
This may or may not relate to the other issue I posted this morning. Had a fresh install running and got this error advisor dialog from Bitdefender:

The file C:\Path\To\Kodi\addons\script.module.thecrew\lib\resources\lib\modules\client.py is infected with Trojan.Generic.31710459 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

Fresh install of The Crew pulled directly from https://team-crew.github.io

**Comment by fade2gray** [comment]
What version of TC AddOn and TC Module versions are being installed? I'm not experiencing any issues with AddOn 1.1.6b and Module 1.1.6n.

Also, you haven't installed TVAddons by any chance - see https://github.com/team-crew/team-crew.github.io/issues/65#issuecomment-915916219

**Comment by EvilCaptKirk** [comment]
Closing this. Looks like a false positive was generated by Bitdefender - they must have recently updated their sigs or algos as I found several quarantined files in the BD log. Just added an exception to ignore The Crew.
