### ISSUE TITLE
Trakt API Usage:  Extremely high use of shows/episode_ratings

### ISSUE THREAD

**Issue by rudf0rd** [team-crew/team-crew.github.io#107]
Hey, I'm a dev at trakt.tv and found that your app is using an incredibly high amount of traffic to the episode ratings endpoint.  It is 81% of your applications entire traffic.

Can someone verify that everything is working as intended and that some level of local caching is being used?

Thanks and please let me know if I can be of any assistance!

**Comment by SilverHat-TC** [comment]
> Hey, I'm a dev at trakt.tv and found that your app is using an incredibly high amount of traffic to the episode ratings endpoint. It is 81% of your applications entire traffic.
> 
> Can someone verify that everything is working as intended and that some level of local caching is being used?
> 
> Thanks and please let me know if I can be of any assistance!

Being looked at, thanks for bringing it to our attention.
