### ISSUE TITLE
Optimize Add-Ons / Repo for Kodi 20 (Nexus Build) [Compatibility]

### ISSUE THREAD

**Issue by RFL0WGitPR** [team-crew/team-crew.github.io#110]
**// Issue**

One or two Add-ons from the Crew Repo failed to install (tried to installed them manually via zip Installation wouldn't install) I guess most of them are supported all the way till Kodi 19 "Matrix".

- Add On: The Crew Repo 0.3.4
- Program Add On: The Crew Wizard 1.1.7
- Video Add On: The Crew 1.1.6.b
- Video Add On: WatchNixtoons2 doko-07.0

Since Kodi 20 will soon be in Beta phase will you kindly consider Optimizing the Add Ons and Repo to work and be compatible for Nexus Build (Kodi 20). 

**//Why apply these changes** 

Kodi 20 "Nexus" is the next major release and their will be a lot of demand for it since Kodi is multiplatform will be nice if the Add-Ons and Repo is already optimized and compatible to work with next build multiple platforms would benefit using your add-ons.

I hope the development team can consider this feedback for future updates 

Thank you

**//My Device specs**

Add On: The Crew Repo 0.3.4
Program Add On: The Crew Wizard 1.1.7
Video Add On: The Crew 1.1.6.b
Video Add On: WatchNixtoons2 doko-07.0

Kodi ver. 20 Alpha 3 "Nexus" APK [Git]
Platform: Android TV 9 (Pie)
Device : TCL Model - 50S434 [4K UHDTV - HDR].
CPU: 4x ARM Cortex-A55 @ 110 MHz 64-bit ARMv8-A (32-bit mode)
Screen Resolution: 1920 x 1080p (45/45 dpi) 
GPU: Mali-470 MP (OpenGL ED 2.0 35f8d2d).
RAM: 2GB "2048MB"

**Comment by thecrewwh** [comment]
Kodi 20 is a long way from being stable But yes they will be optimized for it once a stable release is out

**Comment by RFL0WGitPR** [comment]
Thank you 👏🙏

**Comment by thecrewwh** [comment]
So i went and tested I know the wizard needs to be updated but the repo and module and crew addon do work just fine nixtoons also works
