### ISSUE TITLE
"No information" available on thumbnails from Real Debrid "lol" section

### ISSUE THREAD

**Issue by TrillaG** [team-crew/team-crew.github.io#111]
Lately I haven't been able to get the thumbnails for the porn section of Real Debrid on The Crew. Everything's up to date and was working just a few days ago.

**Comment by ur-vile** [comment]
Also having this problem. 

Pretty much nothing works in the "recent videos" section, can't get anything to play.

"popular this week" seems to work, but no thumbs, same with "popular this month".

"Sites A-Z" is just kinda generally messed up. Some stuff works. some stuff doesn't. filenames are weird.

I think there was an update to some dependency that screwed the pooch.

**Comment by monkey1616** [comment]
I was having the same problem however the links are working today but still no thumbnails

**Comment by ur-vile** [comment]
Yeah seems like vids are playing in "recent video" now, but no thumbs, and filenames are still messed in "sites A-Z"

**Comment by monkey1616** [comment]
Yes same here

**Comment by ur-vile** [comment]
So I opened up an older kodi install that does not have automatic updates, it's on The Crew 1.1.5 (current is 1.1.6q). Same problem on the older version.

Only dependencies listed on current version is Beautiful Soup and Soup Sieve, neither of which look like they've been updated for some time (same version on current and old install). I have no idea what the implications for that are, but those are my findings.

**Comment by fade2gray** [comment]
See this for support - https://github.com/team-crew/team-crew.github.io/issues/108#issue-1427802412

**Comment by monkey1616** [comment]
I still don't have thumbs for the adult section under recent

**Comment by thecrewwh** [comment]
Fixed
