### ISSUE TITLE
All playback freezes 17secs in including Kodi

### ISSUE THREAD

**Issue by JustDawn** [team-crew/team-crew.github.io#112]
Firstly, I've finally built up the courage to post, so please be kind 

2015 Shield Pro/Android 11/Kodi 19.3/newest Crew repo/PM/no missing dependencies/no error messages.
5mos back I was running Kodi 18.9 and PM was scraping tons of results, but nothing would play. Error saying python... bla bla bla, couldn't be found. 
Via Reddit posts I was told that the required python version no longer supported Kodi 18. and I needed to load 19. so I bit the bullet and did so.

From then on the python error message stopped, but so did   everything else. Kodi started freezing about 17 secs into playback. I haven't been able to watch anything via Crew since. 
I loaded The Promise and it worked for a week or so but if hit pause at any time during playback Kodi would freeze and I'd hard close.  Now Promise is doing the same thing as Crew. Afterward it's not showing up in my PM Cloud either. 

At the end of the day, I have to go to PBay, grab a magnet and watch via PM Player. The only time anything will play longer than 17-60 secs via Kodi is if I actually download it.  

Phew.... Sorry for the novel, but I'm at a loss and don't know what to do at this point. HELP!

**Comment by fade2gray** [comment]
See this for support - https://github.com/team-crew/team-crew.github.io/issues/108#issue-1427802412

**Comment by JustDawn** [comment]
Thank you. All repos are doing it now. It's got to be the Shield. Kodi and crew are working fine on all other devices. 😖🤬🤬

**Comment by fade2gray** [comment]
Not that it's any consolation, it seems others have had issues with Kodi on a Shield. Just wondering if you actually tried a clean installation of Kodi Matrix 19.x rather than updating from 18?
