### ISSUE TITLE
MORIA addon

### ISSUE THREAD

**Issue by eeden003** [team-crew/team-crew.github.io#115]
Why o why has The Crew Repo more and more similair addons that do thesame ? What is the extra value of a lot of addons that find series/movies ? I do not get it. please explain, thanks.

**Comment by thecrewwh** [comment]
The only add-ons provided by the crew is the crew and purely wrestling the others are by others that we host they are good and do provide some different lists but I get what your saying thanks look at the name on the admins you can which are the crews
