### ISSUE TITLE
Search function not working

### ISSUE THREAD

**Issue by leeroyed** [team-crew/team-crew.github.io#116]
Since about a week now , nothing comes up, no matter what is searched

**Comment by fade2gray** [comment]
It's because of the current issue with Trakt being down, and is also affecting other add-ons.

![Trakt](https://user-images.githubusercontent.com/1332009/208435870-a402831c-544c-450f-bd30-50668e66e8b8.png)

**Comment by fade2gray** [comment]
There is a work-around, though. If you know any of the actors names, you can search for `People - Movies` or `People - TV Shows` and it will list everything they've appeared in.

**Comment by leeroyed** [comment]
> There is a work-around, though. If you know any of the actors names, you can search for `People - Movies` or `People - TV Shows` and it will list everything they've appeared in.

Thanks alot , a love the crew i have it on 7 devices now! one other small question , why does buffering take so long on Xbox? both my Series X and old ONE take an age to even pull up the search keyboard ,while my PC's and Phone are very fast

**Comment by fade2gray** [comment]
I'm only familiar with Windows PC and Raspberry Pi, but if you have a Telegram messenger account, see #108.

**Comment by onknight** [comment]
You can check the status of Trak here https://status.trakt.tv/ also on Twitter https://twitter.com/trakt

** according to the latest Twitter post
they are planning to slowly turn on the public API tomorrow morning PST.**

Hoping this helps since I've done a Fresh build of K O D I  and need to reauthorize

**Comment by onknight** [comment]
it's working now I just was able to reauthorize
