### ISSUE TITLE
Virus warning - false positives?

### ISSUE THREAD

**Issue by Admin-A-LLC** [team-crew/team-crew.github.io#117]
I'm getting virus warning from modules for kodi builds and just plugins by you guy's work. Thought I should mention it since it's Microsoft Defender reporting it and damn near everyone has that on their computer. 

![Screenshot 2022-12-24 153338](https://user-images.githubusercontent.com/16944595/209453350-e8543685-b6a9-4b37-b175-8747a3b7a491.jpg)
![Screenshot 2022-12-24 153651](https://user-images.githubusercontent.com/16944595/209453351-239444f4-a364-4799-a0c6-16aeb7266021.jpg)

**Comment by fade2gray** [comment]
> Its false. It's because the files are obfuscated
> Ignore it
> ^^^^Posted by Crew admin on their Telegram group^^^^

https://www.reddit.com/r/Addons4Kodi/comments/yxffov/anyone_elses_antivirus_get_tripped_up_with_the/
