### ISSUE TITLE
Problem on running the addon

### ISSUE THREAD

**Issue by PetrosMAMALIOGKAS** [team-crew/team-crew.github.io#119]

**Comment by PetrosMAMALIOGKAS** [comment]
Wrong please delete

**Comment by PetrosMAMALIOGKAS** [comment]
Actually I do not have the rights to remove this issue #119

**Comment by fade2gray** [comment]
Strange, I was able to delete the comment I posted.

You've closed the issue, and it's not causing any problems - don't worry about it, because it's not going to worry the repo author.
