### ISSUE TITLE
Python/MCCrash.B!MTB

### ISSUE THREAD

**Issue by Boac** [team-crew/team-crew.github.io#121]
Many people getting this trying to install Crew on Windows and it being blocked.  Severe Threat: Python/MCCrash.B!MTB

**Comment by fade2gray** [comment]
False positive, you need to allow an exception for it.

https://www.reddit.com/r/Addons4Kodi/comments/zxp32g/possible_trojan_virus_from_the_crew_just_in_case/

**Comment by Boac** [comment]
I did that and all good. Posted your reply on other forums and reddit threads as well. Thanks for your time.
