### ISSUE TITLE
The Crew addon

### ISSUE THREAD

**Issue by Sobersally** [team-crew/team-crew.github.io#122]
I am having an issue with The Crew. It was working fine about a week ago but I had some addon problems and now I reinstalled Kodi 19.5 and it gives me an error.  It is a python interpreter error for the addon. It says it cannot import name from resources.lib.modules. I hope that helps. Fresh install.

**Comment by JLQ5817** [comment]
> > Hello, I have the same issue with the fire stick tv. Please check this error log.![image](https://user-images.githubusercontent.com/123281125/213898447-a5837d50-8f00-434a-a19e-3dddebfd698b.jpeg)
Thank

**Comment by fade2gray** [comment]
The Crew add-on development always tends to lag behind Kodi version updates. I would try to revert back to Kodi 19.4 if you can.

You can also try contacting the TC team by using the link [here](https://github.com/team-crew/team-crew.github.io/issues/108), but you will need a [Telegram](https://telegram.org/) messenger account.

**Comment by thecrewwh** [comment]
Windows defender issue
