### ISSUE TITLE
Cannot connect to the repository

### ISSUE THREAD

**Issue by paradoxgrowth** [team-crew/team-crew.github.io#123]
Hi

Thanks so much for building this add in. I have the repository installed in my kodi 19 installation. Unfortunately, kodi cannot connect to it to install the crew add in. Does anyone know if it’s down or being blocked? I am in the US and have Cincinnati Bell as my ISP.

Any tips or is there a direct link to the zip file?
 Thanks!

**Comment by fade2gray** [comment]
What Kodi version - 19.4, 19.5?

**Comment by paradoxgrowth** [comment]
19.4

**Comment by fade2gray** [comment]
Outside my scope, I would try contacting the devs via Telegram, as mentioned [here](https://github.com/team-crew/team-crew.github.io/issues/108).

**Comment by paradoxgrowth** [comment]
Thanks fade2gray
