### ISSUE TITLE
Error on The Crew Addon 

### ISSUE THREAD

**Issue by Iamrondeau** [team-crew/team-crew.github.io#127]
I had managed to fix the first error regarding windows defender. Now I have a new one.

https://paste.kodi.tv/ewawugomux

If anyone can assist I cannot figure this one out.

Plugin.Video.The crew failed could that be the problem 

Thank you

**Comment by fade2gray** [comment]
Possibly Defender has quarantined some files, take a look at https://github.com/team-crew/team-crew.github.io/issues/125#issue-1558480415

**Comment by Iamrondeau** [comment]
This was the first error in the log that I had fixed by allowing the folder in defender, this stopped the error from happening.

Now I have a new one and defender does not have a play, as I checked defender and there were no threats reported.

One thing that I see in the log is error that shown failed:

Plugin.video.thecrew

**Comment by fade2gray** [comment]
Try adding an exception for `C:\Users\CRondeau\AppData\Roaming\Kodi\` in Virus & threat protection settings.

Other than that, try contacting the devs on Telegram - see #108.

**Comment by Iamrondeau** [comment]
I had to give up as nothing else is working and the error keeps showing up. Installing Kodi in the firestick fixed this issue.
