### ISSUE TITLE
Scrapers other than torrent not working

### ISSUE THREAD

**Issue by JaxJoe01** [team-crew/team-crew.github.io#13]
A few things - 
1.  Scrapers other than torrent are minimally working.  I think about 3 non-torrent will show most urls but the rest show nothing.  If jumping on a computer, searching those sites, working links are there for various shows that do not work in the crew.  Are these maintained by the crew or are they 3rd party scrapers?

2.  For the above, if they are part of the crew or 3rd party scrapers, do you have a pointer or how-to?  Would love to get into it and work on assisting updating the code if needed.

Either way, dropped all other addons for this as this (in my eyes) is the best one stop shop for everything.  All your work is very much appreciated.

**Comment by UPRHome** [comment]
Noticing an issue with Watched History not being identified (checked) after watching a TV show. Attempting to manually "Mark as watched in The Crew" is unsuccessful and can make the system hang

**Comment by thecrewwh** [comment]
Will take a look lots of sites go up and down
