### ISSUE TITLE
Duplicate seasons

### ISSUE THREAD

**Issue by drrak** [team-crew/team-crew.github.io#137]
_Translator:_
Series, and more precisely, seasons and episodes are duplicated.
Some seasons are missing.

**Comment by fade2gray** [comment]
I'm seeing the same. I initially thought it was a Trakt problem, but other add-ons that use Trakt aren't affected.

**Comment by eeden003** [comment]
Same problems here in Europe with The Crew addon, multiple users on user-groups report this issue. Also......no new episodes with several addons including The Crew when using free links.

**Comment by fade2gray** [comment]
Apparently, it's an issue with TVDB for which the crew is working on a fix.

**Comment by fade2gray** [comment]
Just posted by WhiteHat.

> We are testing and almost ready to push a update

**Comment by drrak** [comment]
There are no more duplicates, but another, smaller problem has arisen. IMDb series also loads movies.
