### ISSUE TITLE
Crew not playing streams from library

### ISSUE THREAD

**Issue by mytechguyri** [team-crew/team-crew.github.io#138]
Just in the past 2 days, (recent update perhaps?) when playing streams from my library, i get the usual "crew will find your links" it finds well over 100 sources, removes duplicates, then simply pops up the playback failed dialog.   If i open The Crew from addons and search and play from there, everything plays normally.   It only fails when playing from my library.   I tried deleting and re-adding to my library, but it still fails to play.   The log isnt showing anything

**Comment by murphy1969** [comment]
having the same issue

**Comment by mytechguyri** [comment]
So finally got a log file. The error that.is coming up is

[ The Crew ]: Could not load "ororo": 'tuple' object has no attribute 'encode'

**Comment by fade2gray** [comment]
Excuse my ignorance on this, but how do you actually add a 'stream' to the TV Shows or Movies libraries?

I mean, I can download Movies and TV Shows which can be found in their respective libraries to be watched offline, but if I use the context menu to add a title to the library from a search result, The Crew says it's been added, but nothing can be found in the library even after updating it.

¯\\_(ツ)_/¯

**Comment by fade2gray** [comment]
According to the TC Telegram channel, it's being worked on.

**Comment by mytechguyri** [comment]
> According to the TC Telegram channel, it's being worked on.
> 
> Alternately, you could use the context menu `Add to Favourites`, which I tend to use anyhow.

How does one find the TC telegram channel?   Ive searched and am not finding it

**Comment by fade2gray** [comment]
The Crew devs rarely respond in here, it would be best to contact them using [Telegram Messenger](https://telegram.org/) app.

See #108 - despite comments, the link is still valid.

**Comment by NikonicImagery** [comment]
having same issue
