### ISSUE TITLE
The Crew won’t open - Memory leak warning in log

### ISSUE THREAD

**Issue by manrata** [team-crew/team-crew.github.io#140]
Again suddenly the Crew won't open, had this error before, then Windows Defender had quarantined some files, see: https://github.com/team-crew/team-crew.github.io/issues/125

This time there aren't any quarantined files.

Kodi version is 19.4.0
The Crew version 2.0.0
Windows 10

The error occurs the moment I try to open The Crew, it just tell me to check log for error.
Error as at bottom in log, the vary a bit, but most are like this.

I've tried clearing cache using Open Wizard, I've checked Windows Defender for quarantined files, and there is nothing.
Also tried completely disabling Windows Firewall, and no changes.
I don't use any other security, since the PC is just a mediaplayer. 
I don't use Trakt.

Any suggestions to what is fucking Python?

----------

2023-05-22 20:35:31.242 T:10476   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'resources.lib.modules.control' has no attribute 'startupMaintenance'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\trust\AppData\Roaming\Kodi\addons\plugin.video.thecrew\service.py", line 64, in <module>
                                                       control.startupMaintenance()
                                                   AttributeError: module 'resources.lib.modules.control' has no attribute 'startupMaintenance'
                                                   -->End of Python script error report<--

**Comment by fade2gray** [comment]
I think your problem may be that you are still using Kodi 19.4 - I believe the latest TC updates are Specifically for Kodi 20 Nexus.

**Comment by manrata** [comment]
Oh, I’ve avoided updating because it didn’t work on newer versions previously.
I’ll update Kodi and see if that solves it.

**Comment by manrata** [comment]
Updated to 20.1, this resolved the issue, thank you, closing this.
