### ISSUE TITLE
Latest TV Episodes yield older episode

### ISSUE THREAD

**Issue by markosjal** [team-crew/team-crew.github.io#141]
I have become aware of an issue where the Crew addon is not showing the latest episodes of TV series.

when I click on an episode from a week ago the links appear but all seem to yield results from about 2 months ago. This I tested on Ted Lasso, and NCIS as well as some others.

I have tested this on Kodi 19.5 and Kodi 20.x

Not only is The Crew affected by this bug but not appears that other addons are having the same issue. There are some threads on reddit about it but no solutions.

**Comment by markosjal** [comment]
yes but try playing the episode from a week or two ago and you get an episode from March. All APPEAR in the list but most recent episodes yield older episodes when opening the link.

Yes they

**Comment by eeden003** [comment]
Well, I use a addon that has had three updates this week, and the 1st update solved the problem that The Crew still has, and the 2nd and 3rd addon were again usefull updates. Very strange that The Crew is só populair but still has big faults, and....a lót of addons in the Repo that are all almost thesame, it is better to make ONE GOOD addon that gets regular updates !

**Comment by markosjal** [comment]
what is the working addon?

**Comment by eeden003** [comment]
ScrubsV2 with FREE links (version ( 5.1.26)(Repo 1.6.0)

**Comment by fade2gray** [comment]
@markosjal 

> It does not sound like you went any further than displaying the links let alone confirm you were seeing the right episode.

Not having watched any of Ted Lasso, I wouldn't know if the wrong content was being played, but I did not find the issue you describe when playing earlier episodes from other series that I follow.
