### ISSUE TITLE
Feature request - DaddyLive Addon

### ISSUE THREAD

**Issue by markosjal** [team-crew/team-crew.github.io#142]
request the ability to generate an m3u file list of channels so that not can be loaded into IPTVMerge or IPTV Simple client.

Links need not reveal actual stream address, but is preferred to get the real link instead of the plugin path link. Note that Kodi has the ability to process plugin path links that are like plugin://daddylive/streamName

**Comment by fade2gray** [comment]
The Crew devs rarely respond in here, it would be best to contact them using [Telegram Messenger](https://telegram.org/) app.

See #108 - despite comments, the link is still valid.

**Comment by markosjal** [comment]
Thats nice but telegram wants new to install an app even on desktop and I do not have a need/use for telegram as it is just another platform that I do not like nor want.
