### ISSUE TITLE
The Crew Debid links

### ISSUE THREAD

**Issue by IsoxSlow** [team-crew/team-crew.github.io#144]
The crew porn section "debrid links: sites A-Z" is no longer working for me unsure if its an app thing or a me problem

**Comment by fade2gray** [comment]
The Crew devs rarely respond in here, it would be best to contact them using [Telegram Messenger](https://telegram.org/) app.

See #108 - despite comments, the link is still valid.

**Comment by IsoxSlow** [comment]
thanks

**Comment by bcresswell** [comment]
Unable to retrieve links when Crew is running. Real debrid cnx is fine. Any suggestions?

**Comment by fade2gray** [comment]
I'm using Real Debrid with no issues - the only thing I can suggest is to reset all settings back to default.

**Comment by bcresswell** [comment]
I don’t have a problem with real debrid. Works fine with other addons. The
Crew addon will not access anything. If I tap “movies” I get “working” then
stops. Nothing is accessed. I’ve tried reinstalling, fresh start, etc.
Earlier versions of Kodi. All this occurred in May. Also defaulted all
settings in crew. Can’t figure this out.
Thanks for your response.

**Comment by fade2gray** [comment]
You are using Kodi 20.x Nexus with TC fully updated - I don't think TC is backward compatible?

**Comment by bcresswell** [comment]
No it isn’t. I have tried an earlier download zip. Won’t work. Also tried
fresh start  on RPI 4 in K v20. No luck either. Only other option maybe
19.5 or 18.5. Only problem is there’s not much left for 18.5. Thanks very
much for your response

**Comment by fade2gray** [comment]
Are you using LibreELEC on your RPi4? If so, make sure you update LibreELEC to 11.0.1

**Comment by bcresswell** [comment]
I think so. I’m not very tech savvy. I use OSMC with Kodi and use the
latest updated osmc windows download onto a usb stick when I fresh install.
How would I chk that? Thanks again

**Comment by bcresswell** [comment]
Not sure what to do here. Any suggestions?

**Comment by fade2gray** [comment]
You failed to mention whether tried updating OSMC using the link to the [guide](https://osmc.tv/wiki/general/keeping-your-osmc-system-up-to-date/)(<- click on the blue text). You don't have to update using a USB stick - that's just for the initial instalation.

**Comment by bcresswell** [comment]
Yes osmc is fully upgraded to Kodi 20.1 as of June 3 2023

**Comment by fade2gray** [comment]
I've posted a message on the Telegram channel for you - maybe someone will come up with a solution.

**Comment by thecrewwh** [comment]
the site changed I have just fixed it let me know if there are still issues

**Comment by bcresswell** [comment]
The crew still will not even load now. Have reloaded zip,repo and addon.
All dependencies listed have been upgraded and installed. I get the
following log error. Home/osmc/.Kodi/addons/script.module.the
crew/lib/resources/lib/modules/crew.py,line 19
Also same…log_utils.line 26 and control.py line 24 and crewruntime.py
line253 and crewruntime line69 and crewruntime line 103 and crewruntime
line139 in get kodi version.
Have you another site?
Thanks so much

**Comment by bcresswell** [comment]
I'm still confused. Do I need to change anything from this end?

**Comment by fade2gray** [comment]
Here's a quote from Classy on TC's Telegram channel.

> OSMC, latest version 1-6-2007 is just too unstable (wifi and wired connection) to get a normal file playing. It's not Kodi, it's not "The Crew", the entire system is unstable and the connection drops at unregular intervals. LibreElec, just works, as always, on a raspBerry and on Hyper-V (mind you, OSMC has no ISO and no x86-x64 support so it can't be hyper-v't) LibreElec would be the best choice on a Pi (4 which i tested)

And I'll repeat what I said above...

> Oh, and to be honest, my advice is to start from scratch with LibreELEC - I tried OSMC years ago and didn't get on with it.

I don't think you'd regret it.
