### ISSUE TITLE
WatchNixtoons2: Search not working

### ISSUE THREAD

**Issue by AceKiron** [team-crew/team-crew.github.io#147]
Currently using the search feature yields no results regardless of what you type in as search query.
![image](https://github.com/team-crew/team-crew.github.io/assets/39498818/7844a201-46e5-420b-8930-d6573cbd6253)

**Comment by TaeterTots** [comment]
Same here … still down. I’m using a web based site till the fix

**Comment by fade2gray** [comment]
I doubt it'll get fixed until someone reports it.

The Crew devs rarely respond in here, it would be best to contact them using [Telegram Messenger](https://telegram.org/) app.

See #108 - despite comments, the link is still valid.

**Comment by AceKiron** [comment]
Well I don't use Telegram and don't plan to make an account just for this. Do they also happen to use Discord?
