### ISSUE TITLE
No sources after update

### ISSUE THREAD

**Issue by drrak** [team-crew/team-crew.github.io#148]
My best source is missing. Unfortunately, I have already forgotten the name of this source.

Is it possible to download an older version of The Crew somewhere?

**Comment by fade2gray** [comment]
The Crew devs rarely respond in here, it would be best to contact them using [Telegram Messenger](https://telegram.org/) app.

See #108 - despite comments, the link is still valid.

**Comment by drrak** [comment]
I watch various movies and series. The most popular ones too.

Yes, I have the latest version of Kodi.

**Comment by cfcc2020** [comment]
I am having the same issue. No links at all in most shows (I watch new and old shows). Only a few shows have links. The same thing is happening on Moria which I assume is being developed by the same people.
Any chance of solving this? It's rather annoying having to download the shows instead of just watching them on Kodi.
Any help will be much appreciated.
I have Kodi 20 on three different devices and the issue is on ALL devices.

**Comment by fade2gray** [comment]
Can it be assumed that you are using a premium service such as debrid, as there are very few 'free' providers any more?

I have no issues using TC with a debrid account on Win10, RPi4 and Android devices running Kodi Nexus.

Can you give an example of a show you have issues with.

**Comment by drrak** [comment]
> Can you give an example of a show you have issues with.

I will give only one example that I remember well.
[Knight Rider series](https://www.imdb.com/title/tt0083437/?ref_=nv_sr_srsg_0_tt_8_nm_0_q_Knight%2520raider). Before the update there were four possibilities, now there is one that doesn't work.

**Comment by fade2gray** [comment]
Try an addon called Seren, I use that when I can't find older stuff on TC - you'll need debrid and Trakt accounts - they also provide torrent links for full season downloads.

**Comment by cfcc2020** [comment]
I don't have debrid. If I have to pay, I'll pay for Britbox
Examples of show with zero links (I had to download them):
The Tower season 2 (2023)
Succession's last season had no links (I had to download), but now it does (unstable to say the least)
Van Der Valk Season 3 (2023)
MidSomer Murders' last season (2023)
Love Hate (2015)
Lewis 
Inspector Lynley Murders
Father Brown's last 5 episodes
The Coroner
Murder in Suburbia
The Bay Season 4 (2023)

Like I said I am experiencing the same thing on Moria.

I have Nexus running on one Win10 and two android devices. The issue is persistant on ALL devices

**Comment by fade2gray** [comment]
If your 'free' source has pulled the plug, which most have done over the last couple of years, then you're going to have to suck-it-up and pay the 60 quid a year for Britbox - or you could pay 35 quid a year for Real Debrid and get a lot more for your money.

¯\\_(ツ)_/¯

**Comment by drrak** [comment]
The most important sources are missing only by updating. An older version of The Crew is needed and everything will be back to normal.

**Comment by fade2gray** [comment]
So, what version of TC did you wind back to?

**Comment by drrak** [comment]
I don't remember. The version before the big changes. I believe it was before May 21.

**Comment by fade2gray** [comment]
I posted this on TC's Telegram account.

> Hi, there's a couple of users on GitHub complaining that their favourite 'free' sources are missing since the last update.
> Edit: One user reckons they 'fixed' it by winding back to a TC version prior to the "big changes".

The Crew devs rarely respond in here, it would be best to contact them using [Telegram Messenger](https://telegram.org/) app.

See #108 - despite comments, the link is still valid.

**Comment by thecrewwh** [comment]
Delete the user data for the crew

**Comment by cfcc2020** [comment]
@thecrewwh How do you delete the user data, by deleting the plugin.video.thecrew folder from the addon_data folder? Please confirm. Thanks!

@drrak How do you go back to an older version and where do I find it. Thanks!

**Comment by cfcc2020** [comment]
@thecrewwh UPDATE!!! Deleting the user data did NOTHING to solve the issue.

Like @drrak said, everything was working great a few weeks ago (must have been since that big update).

And again, the same thing is happening on Moria.

Please, help us solve the issue. It's a pain having to download stuff.

**Comment by drrak** [comment]
> @thecrewwh UPDATE!!! Deleting the user data did NOTHING to solve the issue.
>

I confirm.

**Comment by cfcc2020** [comment]
@drrak How do you go back to an older version and where do I find it. Thanks!

**Comment by drrak** [comment]
> @drrak How do you go back to an older version and where do I find it. Thanks!

I don't have the old version. I was hoping to find this version here.

**Comment by cfcc2020** [comment]
@drrak Ok, thanks. I misunderstood, sorry!

**Comment by cfcc2020** [comment]
So, the issue is still unresolved, then. Please help!!

**Comment by fade2gray** [comment]
What don't you understand? The `free` host that provided the source no longer exists - even if you could install an older version of TC, it won't bring the host back online - you'll have to go with debrid or similar.

**Comment by cfcc2020** [comment]
> What don't you understand? The `free` host that provided the source no longer exists - even if you could install an older version of TC, it won't bring the host back online - you'll have to go with debrid or similar.

First of all, there is NO need to snap and act like an asshole. I was under the impression that these forums were here to help.

Second, a few responses ago you said; "If your 'free' source has pulled the plug, which most have done over the **last couple of years**". Well, ALL the FREE links were working perfectly fine about three WEEKS ago (NOT a couple of YEARS ago).

So, if all the FREE links were working perfectly fine about three weeks ago, which is the approximate time of that big update, it is only reasonable to think that the update itself created the issue that we are talking about here.

Now, if the issue cannot be resolved, so be it, but do NOT tell me I do NOT understand. 

If anybody can help with this issue I'd appreciate it greatly. Thank you in advance!

**Comment by fade2gray** [comment]
@cfcc2020 

1. I'm just an end-user like yourself.
2. I try to provide advice based off my own experience where I can, and when I can't be of help, I provide a link to contact the TC devs (which I did further up the thread).

If you want support from the TC devs, see...

![TC_GitHub](https://github.com/team-crew/team-crew.github.io/assets/1332009/f7680eea-9bd2-4fea-aae4-04517fcd0eb1)

**Comment by cfcc2020** [comment]
I am still having the issue. No links in a lot of the shows including season 2 of The Tower (2023), but especially shows that are older than, say, 5 years or so.
If anybody can help I'd appreciate it. Thanks

**Comment by fade2gray** [comment]
It has been explained that the developers rarely visit this repository. If you want support from anyone other than an end user, you need to take it up with the developers on TC's Telegram channel.

**Comment by drrak** [comment]
The problem is back.

**Comment by thecrewwh** [comment]
Go to telegram group
