### ISSUE TITLE
Trying to watch latest episodes yields older episode

### ISSUE THREAD

**Issue by PhatPhantom** [team-crew/team-crew.github.io#150]
I have tried to watch latest TV episodes in the crew addon and any newer episode seems to give me an episode from months before.

this is the same on Kodi 19.x on Libreelec and Kodi 20.1 on Windows

**Comment by fade2gray** [comment]
1. You need to update LibreELEC to 11.0.1, so you can update to Kodi Nexus.
2. Check that Windows Defender hasn't quarantined any files during updating Kodi / TC.

If you want support from the TC devs, see...

![TC_GitHub](https://github.com/team-crew/team-crew.github.io/assets/1332009/f7680eea-9bd2-4fea-aae4-04517fcd0eb1)

**Comment by classymouse** [comment]
since the latest version (plugin 2.0.2/module 2.0.5/artwork 2.0.0 and higher), defender is no longer an issue ;-)

**Comment by PhatPhantom** [comment]
Well since others have posted similar questions and I have the same issue with Kodi 19 and Kodi 20 on both windows and Linux I do not believe for a minute that it is resolved

**Comment by PhatPhantom** [comment]
Sorry Installing for and registering yet another app that I do mot otherwise use should not be a requirement to try to get some help.

**Comment by thecrewwh** [comment]
There is no issues it is on your end try completely removing the addon and userdata
