### ISSUE TITLE
No sources after update Part 2

### ISSUE THREAD

**Issue by cfcc2020** [team-crew/team-crew.github.io#152]
I am still having the issue of no sources after the update of about a month ago in a lot of shows that had plenty before the update. 

Please see issue #148 

No links in a lot of the shows including season 2 of The Tower (2023), but especially shows that are older than, say, 5 years or so.

If anybody can help I'd appreciate it. Thanks

**Comment by fade2gray** [comment]
It has been explained that the developers rarely visit this repository. If you want support from anyone other than an end user, you need to take it up with the developers on TC's Telegram channel.

**Comment by thecrewwh** [comment]
We are all getting links try deleting the crew userdata

**Comment by drrak** [comment]
Translator:
I checked [The Tower](https://www.imdb.com/title/tt14364876/?ref_=wl_li_tt)  series and there are no links. But I don't know if they've ever been here.

**Comment by thecrewwh** [comment]
<img width="1512" alt="Screenshot 2024-01-05 at 2 37 36 PM" src="https://github.com/team-crew/team-crew.github.io/assets/57910910/48905f38-d3d6-42bc-b70f-afe718933644">
Works fine try deleting all kodi data
