### ISSUE TITLE
Invalid Orion API key

### ISSUE THREAD

**Issue by baltzis** [team-crew/team-crew.github.io#158]
When scraping with the **Chains Genocide** addon included in _The Crew repo_, Orion produces the message **'Invalid app API key'**. The Orion team suggested that the Orion API key used in Chains Genocide has been copied from another addon - and therefore requests get blocked. The Chains Genocide developers need to get their own API key which can be requested for free on the Orion website.

**Comment by thecrewwh** [comment]
I will let them know
