### ISSUE TITLE
Homelander Scrapers update 1.2 8 removes free Hosters.

### ISSUE THREAD

**Issue by justmejustme** [team-crew/team-crew.github.io#159]
When you update Homelander Scrapers to version 1.2.8, run the "Clean Settings file, 16 old entries are removed. Then go to Homelander Scraper settings, it has no Hosters tab. Try to play any popular TV show and no links are found. Is Homelander now RD only?
I'm using Kodi 19.5

**Comment by justmejustme** [comment]
> The Crew devs rarely respond in here, it would be best to contact them using [Telegram Messenger](https://telegram.org/) app.
> 
> See #108 - despite comments, the link is still valid.

Thanks for the info, I don't use Telegram, perhaps if anyone else has the same issue they could contact them.

**Comment by fade2gray** [comment]
Maybe [this](https://iwf1.com/kodi/script.module.homelanderscrapers) may help?

**Comment by justmejustme** [comment]
> Maybe [this](https://iwf1.com/kodi/script.module.homelanderscrapers) may help?

It updated ok three times, as I was able to roll back my portable installation. Every time the same result . If nobody else has the same issue then it must be at my end, I'll just have to uninstall Homelander. Thanks for your help.

**Comment by thecrewwh** [comment]
Free Has been rem oved from homelander
