### ISSUE TITLE
Purely Wrestling - Aew Collision link not working

### ISSUE THREAD

**Issue by XBoss90** [team-crew/team-crew.github.io#160]
Into kodi Add-on Purely Wrestling into AEW Section, the link to AEW Collision is pointing to "AEW All Access" directory.

**Comment by fuzzbop** [comment]
The problem with this is the xml itself is pointing to allaccess.xml twice, collision.xml works fine if navigated to directly. 
![xmlwrong](https://github.com/team-crew/team-crew.github.io/assets/19721685/273f7c41-18ab-4834-9c2a-e4b7c841791f)

**Comment by thecrewwh** [comment]
fixed
