### ISSUE TITLE
Movies missing/ not displaying correctly by year

### ISSUE THREAD

**Issue by Zee346** [team-crew/team-crew.github.io#167]
Near the beginning of December, I noticed that incorrect/ missing movies were showing up when searching movies by year (example- The Marvels was released in 2023, but when searching it is nowhere to be seen).  This seems to happen for all years chosen.

I have tried uninstalling/ re-installing The Crew, but has not changed.  I am currently running Kodi version 20, and have tried reauthorizibg Real Debrid, but the issue remains.

Hope you can shed some light on this.

**Comment by HyperSin** [comment]
Better then mine i had to completely use a entirely different app because all my crew links will show are 2024+ movies, completely unreleased movies are all mine pull up

**Comment by thecrewwh** [comment]
They show 5 pages in and will be resolved in next update
