### ISSUE TITLE
addon zip file not showing on kodi source

### ISSUE THREAD

**Issue by hezronobuchele** [team-crew/team-crew.github.io#168]
The zip file is not showing up on Kodi with the source `https://team-crew.github.io/`

I'm trying to install Kodi & this repo from scratch and facing this issue. I think this may be related to the update yesterday as the recent version installed fine a few months ago on another device.

Could it be because the target if the link and the link text are different?

```<a href="repository.thecrew-0.3.4.zip">repository.thecrew-0.3.5.zip</a>```

i.e. 0.3.4 vs 0.3.5?

**Comment by fade2gray** [comment]
Apparently, it's "being addressed".

**Comment by benbarker89** [comment]
Following. Got the same issue for a new stick! 😩

**Comment by fulufhel0** [comment]
Am also having the same issue

**Comment by Hobbles1** [comment]
Had the same issue for 2 days. Love this addon. Hope it's fixed soon. Thx for the hard work.

**Comment by lilroshy** [comment]
Had this same issue today :(

**Comment by blibdoolpoolp** [comment]
Nooo!! Same here :(

**Comment by thecrewwh** [comment]
FIXED
