### ISSUE TITLE
unable to unistall indigo..

### ISSUE THREAD

**Issue by p060477** [team-crew/team-crew.github.io#18]
sammydc77:
"I have sent a message to [thecrewwh], that this issue is alive again
[please review the bottom of Issue #8], it would be best to open/create a
New Issue, otherwise it will not be notice be The Crew [since Issues #7 and
#8 have been closed by The Crew].  I am not part of The Crew, and only
offered what help I could, at the time.  This issue went away, after
[fuckindigo v0.0.2] came out."..:

in my case the bug is still open..
no one of  the tricks showed in issues 7 and 8 work for me..
so for me this cold case is still hot and open 
and ALIVE

**Comment by sammydc77** [comment]
The Crew:

Their official support channel is on Telegram: https://t.me/joinchat/MbCgH0kbQ5NqkeIm7JaCZg

You will need a Telegram Account.  This is the fastest way to communicate with them. 

You may also want to follow this on Reddit [for safe add-ons]:

From within Reddit: r/Addons4Kodi [Home]

https://www.reddit.com/r/Addons4Kodi/comments/haam5p/recommended_addons_3rd_quarter_2020/

Good Luck!

**Comment by p060477** [comment]
thxs for yr helping
i really hope that the guys will be able to solve this so frustrating matter
we all love the crew
and we really would like to be able to use it
thxs to you
ALL

**Comment by sammydc77** [comment]
Glad it helped...  Have a good day!
