### ISSUE TITLE
real debrid resolver not working

### ISSUE THREAD

**Issue by kurtjcu** [team-crew/team-crew.github.io#19]
Real Debrid resolver stopped working and shows "L7" when trying to authorise

**Comment by fade2gray** [comment]
Are you trying to authorise a new device?

I have no problem with currently authorised devices using various flavours of Kodi and The Crew, but I'm afraid I won't try re-authorising incase you jinx me. :/

**Comment by fade2gray** [comment]
Just added Kodi on an Android device, set up The Crew and Real Debrid authorisation without any problems.

**Comment by kurtjcu** [comment]
I had 2 devices, both were already authed, both were failing in the same way, tried exodus/crew neither worked. But both are working now, may have been a temporary glitch on RD side of things..
