### ISSUE TITLE
Canadian TV isn't working in the Chains Sinisters Free TV section

### ISSUE THREAD

**Issue by RickFromTexas** [team-crew/team-crew.github.io#21]
As the title says, the channels in the Chains Sinisters Free TV Canadian section aren't working. Thanks, great addon though!

**Comment by thecrewwh** [comment]
I will let him know about that as it is not our addon

**Comment by RickFromTexas** [comment]
Nvm, he pulled all the iptv stuff out except world tv so I uninstalled his addon. Thanks anyway tho, cheers.

________________________________
