### ISSUE TITLE
Live tv still.not working

### ISSUE THREAD

**Issue by joe71101** [team-crew/team-crew.github.io#26]
So last month I opened an issue of ustvgo not working.  No response from the addon author, just simply closed the issue.  No updates to code since may 3rd.  The issues still exist to this day.  Is this add on still viable or should we all look elsewhere?

**Comment by fade2gray** [comment]
That's the repo that hasn't been updated since May 3. It seems like you have your Kodi update settings on the default auto-update for addons, hence you wouldn't notice that the last code update was Oct 12.

![Capture](https://user-images.githubusercontent.com/1332009/98361757-0d5c5b00-2024-11eb-91aa-b4e18251047d.PNG)

You won't see much activity from the devs in here, but you might get a better response by joining the Team Crew Community on [Telegram Messenger](https://telegram.org/).

Good luck. 👍

**Comment by joe71101** [comment]
> @joe71101
> 
> That's the repo that hasn't been updated since May 3. It seems like you have your Kodi update settings on the default auto-update for addons, hence you wouldn't notice that the last code update was Oct 12.
> 
> ![Capture](https://user-images.githubusercontent.com/1332009/98361757-0d5c5b00-2024-11eb-91aa-b4e18251047d.PNG)
> 
> You won't see much activity from the devs in here, but you might get a better response by joining the Team Crew Community on [Telegram Messenger](https://telegram.org/).
> 
> Good luck. 👍

I'm looking at the code on this site.  Unless there is another repo for the crew that I do not know about

**Comment by fade2gray** [comment]
The add-on files are not publicly displayed in the repo, they're contained within the zip file, e.g. [repository.thecrew-0.3.1.zip](https://github.com/team-crew/team-crew.github.io), this is the file that is used to install the add-on when clicking on `Add-ons > Install from zip file` (remember how you originally installed The Crew?). It's those files within the zip file that I said was last updated on Oct 12, but that is not reflected in the zip's "6 months ago", that will only change when there's been a major update and a new repo is released.

Hope that makes sense, and as I said, it could be several months before a dev looks in here, and if you have an issue try using the Telegram Messenger

**Comment by thecrewwh** [comment]
Ustvgo was fixed you won't see a lot of the fixes in updates as they aren't directly in the Addon as to say if it still works the site has been down a lot so I'm not sure what is going on in it and yes you won't see us here ,much you will find us in our telegram group
