### ISSUE TITLE
Won't enable

### ISSUE THREAD

**Issue by frumbert** [team-crew/team-crew.github.io#28]
I've installed the zip then go to addons -> all addons and it shows in the list as disabled. I open it, and press enable. When I close, the repo says disabled again. No amount of restarts / removes / reinstalls will make it work.

**Comment by fade2gray** [comment]
Have a look at issue #7.

**Comment by frumbert** [comment]
The only way I have found to 'fix'  tvaddons is to utterly delete kodi (backing up the db first of course) and reinstalling without tvaddons. otherwise it basically behaves like malware.

**Comment by fade2gray** [comment]
@frumbert 

Yep, that's why I commented "A clean install of 'Kodi' + 'The Crew' = 'no problems since'." in #7
