### ISSUE TITLE
Easynews

### ISSUE THREAD

**Issue by captainfearless** [team-crew/team-crew.github.io#31]
Hi,

Thanks for this great addon.

I don’t get any results when searching, for Easynews, even though my login details are entered correctly.

**Comment by fade2gray** [comment]
@captainfearless 

Hadn't heard of Easynews till your mention, but you won't see The Crew devs answering much in here - you may get a better response from them if you contact them using the Telegram messenger service. I initially experienced great difficulty setting up RealDebrid - maybe your issue may be a simple configuration oversight?

**Comment by thecrewwh** [comment]
All depends what api you are signed up for with easy news
