### ISSUE TITLE
Cannot Get Crew to work or any addon to stream 

### ISSUE THREAD

**Issue by ksalted** [team-crew/team-crew.github.io#32]
Since around 12/27 I have not been able to on my windows 10 desktop computer to get Kodi to stream addon content.  I was using Crew until that time without incident.   My laptop (same windows 10 as desktop) and Mac computer work fine with Kodi and can stream from Crew or other addons.  What happens is I am able to find streams of content and load the stream but then it would crash the computer instead of streaming.  I copied the kodi files from my laptop to my desktop and installed exact version 18.5 that was working on laptop.  Still crashed when attempting to load a stream that I verified was working from laptop computer.    I tried other non crew streaming add ons and builds on my desktop same problem every time.  I checked my firewall settings and they are exactly the same on my windows laptop and desktop.  Both are running the exact version of windows and updates.  All web browser software is also the same.

Any clues would be greatly appreciated?

**Comment by fade2gray** [comment]
@ksalted 

I have a similar setup with Win10 desktop and laptop, Raspberry Pi and several android devices (no Mac) with no issues. The Win10s are running 18.8 but 18.9 Leia is available. I know The Crew is an officially supported add-on, but have you tried asking in the Kodi forums with your chrash logs?

Failing that, I'd try backing up your Kodi settings directory and make a clean install using 18.9 and take it from there.

Note: You will rarely see The Crew devs respond in here. The best way to contact them is through the [Telegram](https://telegram.org/) messaging app

**Comment by thecrewwh** [comment]
Try clean install of Kodi like @fade2gray has said
