### ISSUE TITLE
Distro and Pluto

### ISSUE THREAD

**Issue by ts2art** [team-crew/team-crew.github.io#34]
Hello, i an curious about the Distrotv addon and the Plutotv addon. Dry Bar Comedy doesnt show up on either anymore. It is located in the Entertainment section, and Entertainment does NOT show up. Any help would be appreciated! ! 
Thank you,
Troy

**Comment by thecrewwh** [comment]
I will let the dev of those add ons know

**Comment by ts2art** [comment]
Thank you.... Are they on Github? If so can you give me their info and I
could email them directly in the future?
