### ISSUE TITLE
Working, working, working

### ISSUE THREAD

**Issue by Sobersally** [team-crew/team-crew.github.io#36]
I just reinstalled Kodi 18.9, windows 10, and all my addons. On other Windows 10 machines, the crew works flawlessly, however on this machine, I just reinstalled it on, The crew is very slow when pulling up the searching for links box, and once I watch something, returning to the screen with the list of torrents. It shows working for at least a minute or more. However, as I said, my other machines don't have that issue. With a clean install of Windows and Kodi and all my addons, I don't understand what I can do to fix this. I have a program on my Kodi that is called easy maintenance that runs when I first start it that clears the cache and thumbnails and packages. I do not get an error message so giving you my log doesn't seem appropriate, but I can if you think it will help. 
Thanks for listening
Sally

**Comment by fade2gray** [comment]
Try this... (I use Real-Debrid, so this might not work for you)

1. The Crew Settings > PlayBack > enable Debrid Only  - I think this may be a misnomer and should read Premium Only.
2. If that doesn't speed up returning the list, make a note of any remaining torrent providers that seem to hang toward the end of the search.
3.  Disable those providers here...

![TheCrewSettings](https://user-images.githubusercontent.com/1332009/107535264-7e2d8900-6bb8-11eb-94d3-30bdfb2e22ad.png)

Hope that helps.
