### ISSUE TITLE
The Crew or any other addon Zip files are not loading from internal or external zip file locations with Kodi 19 

### ISSUE THREAD

**Issue by fuddstar2012** [team-crew/team-crew.github.io#40]
Install From Zip gives the following error;
Warning
Note that add-ons installed from zip (excluding served repositories) will not auto-update and must be manually updated.
Would like to proceed ? Yes doesnt not work ?

Please help

**Comment by fade2gray** [comment]
The current version of `The Crew` is not compatible with `Kodi 19`.

If you still want to use `The Crew`, you will need to revert back to `Kodi 18.9`.

#37 #38 #39
