### ISSUE TITLE
NHL Replays not working?

### ISSUE THREAD

**Issue by Acefrehley64** [team-crew/team-crew.github.io#41]
Hi the NHL replays aren’t playing . It has an updated games list but when you click on the game nothing?

**Comment by thecrewwh** [comment]
This will be looked in to also another source was added

**Comment by Acefrehley64** [comment]
Hi NHL Replays ( FM ) is good but has a limited number of games . ( LSX ) has all or most of the games listed but not working ( LSX ) was great when working?
      Thanks,
           Curtis Garner

Sent from my iPhone

On 10/04/2021, at 10:46 PM, thecrewwh ***@***.***> wrote:

﻿

This will be looked in to also another source was added

**Comment by thecrewwh** [comment]
That was fixed earlier today

**Comment by Acefrehley64** [comment]
I like ( FM ) but like i said it has limited games ( not every Montreal game . ( LSX ) had some recent games that worked for me .  I didn’t see the new source you n mentioned . Thanks for taking the time to try to resolve my problem.
    Rock On
  Curtis Garner


Sent from my iPhone

On 23/04/2021, at 9:10 AM, curtis garner ***@***.***> wrote:

﻿ Hi NHL Replays ( FM ) is good but has a limited number of games . ( LSX ) has all or most of the games listed but not working ( LSX ) was great when working?
      Thanks,
           Curtis Garner

Sent from my iPhone

On 10/04/2021, at 10:46 PM, thecrewwh ***@***.***> wrote:

﻿

This will be looked in to also another source was added

**Comment by Acefrehley64** [comment]
Actually 2 out of the 4 recently added games on (LSX ) i could get to work which means there is hope we can get them all working i hope 🤞.
    Thanks again keep up the great work!

Sent from my iPhone

On 26/04/2021, at 4:03 PM, curtis garner ***@***.***> wrote:

﻿ I like ( FM ) but like i said it has limited games ( not every Montreal game . ( LSX ) had some recent games that worked for me .  I didn’t see the new source you n mentioned . Thanks for taking the time to try to resolve my problem.
    Rock On
  Curtis Garner


Sent from my iPhone

On 23/04/2021, at 9:10 AM, curtis garner ***@***.***> wrote:

﻿ Hi NHL Replays ( FM ) is good but has a limited number of games . ( LSX ) has all or most of the games listed but not working ( LSX ) was great when working?
      Thanks,
           Curtis Garner

Sent from my iPhone

On 10/04/2021, at 10:46 PM, thecrewwh ***@***.***> wrote:

﻿

This will be looked in to also another source was added

**Comment by thecrewwh** [comment]
They are all working the site docent have every game so until or if the are added they won't work
