### ISSUE TITLE
Error in "Get Directory" on Kodi Raspberry Pi4b

### ISSUE THREAD

**Issue by jvproduct** [team-crew/team-crew.github.io#44]
Raspberry Pi4B
Kodi 18
New SD Card

When I browse for movies, e.g. "New", "Genres" no list pops up.

Error in log: GetDirectory Error in getting plugin://plugin.video.thecrew/?action=

[log-2021-03-20-11.35.14.zip](https://github.com/team-crew/team-crew.github.io/files/6175431/log-2021-03-20-11.35.14.zip)

**Comment by fade2gray** [comment]
Might sound daft but have you checked Kodi's internet connection status?

`Cog-Wheel > System information > Network`

Otherwise, it may be an issue specific to the Pi4B - I have no problems with the Crew on a Pi2B running Kodi 18.8.

**Comment by jvproduct** [comment]
Yes I did check the network. Other plugins work fine. TC search works and then the movie plays. 
my older PI 2 also works. 

Any other thoughts?

**Comment by fade2gray** [comment]
...only to try backing up / renaming the `pi-home\.kodi\userdata\addon_data\plugin.video.thecrew\settings.xml` file on the Pi4 and copying in the one from the Pi2.

Other than that I'd try a clean install of TC on the Pi4. ¯\\_(ツ)_/¯

**Comment by jvproduct** [comment]
I did copy the settings from the old pi 2. 
And a fresh install with only TC. 
And a fresh install with other plugins. 

I guess it has to do with the hardware or Operating System. Damn.

**Comment by fade2gray** [comment]
You could try enquiring in the [Subreddit](https://www.reddit.com/r/Addons4Kodi/) or contacting Team Crew via the [Telegram Messenger](https://telegram.org/). I've been thinking about getting a Pi4 myself, but am now having second thoughts if TC is likely to be incompatible. 🤔

**Comment by jvproduct** [comment]
Exodus Redux works fine on the pi4. Maybe you could check with them or their code?

**Comment by thecrewwh** [comment]
delete your userdata for the crew
