### ISSUE TITLE
Sports (all) no longer working

### ISSUE THREAD

**Issue by hawkwynd** [team-crew/team-crew.github.io#52]
Fresh install of Kodi latest, with latest The Crew. 
Up until 10 days ago it was working fine and streaming all sports (mlb, etc). 

The First Disclaimer creates a file in my addon_data named `agreed.txt`. Does this have to contain a string? 

When the First Dislaimer window appears, there is nothing showing to click on, no buttons or checkbox in the dialog.

**Comment by thecrewwh** [comment]
Upgrade to kodi 19
