### ISSUE TITLE
Team Crew 

### ISSUE THREAD

**Issue by suzie59** [team-crew/team-crew.github.io#53]
UPDATE:  I GOT MINE TO WORKING JUST DISREGARD REQUEST.. THANK YOU TO THE CREW .....last night my iptv stopped working , it tries to load but doesn't on all fire sticks... i hate this I really love what you boys do...Just thought I would report..it says the plugin failed to load.. thank you for all your hard work... appreciation from me... I'm still using Kodi 18

**Comment by thecrewwh** [comment]
GO to 19
