### ISSUE TITLE
TV Addons have no streams available.

### ISSUE THREAD

**Issue by raffodk** [team-crew/team-crew.github.io#60]
I have different Kodi adddons,Covenant, The Crew, Exodus Redux and have issues with the TV section and it can be any show and I cannot get any streams at all. I have done different versions of Leia, with clean installs.  People have been suggesting to remove  Indigo, but when i search for it, nothing comes up.  I have installed the Indigo removal, F-Indigo but nothing changes.  Cache has been cleared and I have a VPN.  So not really sure what to do here.  Any help would be great.

Thank you

**Comment by fade2gray** [comment]
What platform? Sounds like you may have a corrupt file if it was a previously working installation. Can you not try Matrix or are you stuck with a Pi2? I have no problems with Matrix on windows and Pi4.

**Comment by raffodk** [comment]
Its windows 10 and was using latest version of Leia .  Tried Matrix but
some addons that I want do not work.  I tried another computer, and still
have the  same problem.  I have comcast and a netgear modem/ router.
Checked the settings there too and did not see anything.

**Comment by fade2gray** [comment]
Sounds like you need a clean install. On Win10 I'm just using Matrix and The Crew with no issues.

**Comment by fade2gray** [comment]
I should add that I have to portable installations of Kodi on Win10, Leia for python 2 addons and Matrix for python 3. The Crew repo will install the correct python version of TC addon according to the Kodi version you are running.

It just sounds like you've installed so many similar addons that something got bust.

**Comment by raffodk** [comment]
Yeah that’s possible.  Once more question.  When you uninstall for programs in control panel, there is an option to check to fully remove all files.  Is Kodi truly removed or do I need to do a search and truly remove Kodi?

Thank you

**Comment by fade2gray** [comment]
If you do a full uninstall, it will remove everything.

What I tend to do when necessary. is make a backup of the userdata directory, e.g. `C:\Users\fade2gray\AppData\Roaming\kodi`, do a full uninstall, then after making a clean install you can recover files like `favourites.xml` etc. from you saved userdata.

**Comment by raffodk** [comment]
Yeah prob should do that.  Thank you for the quick responses.

**Comment by fade2gray** [comment]
@raffodk Oh yeah, forgot to say, I'd avoid installing TV Addons again. ⛔

**Comment by raffodk** [comment]
I did try the Kodi mobile and put Matrix on it.  The Crew does find streams but it is only limited to 6 providers.  Is there a way to add providers?  I have tried different TV addons under the Crew and always shows 6 providers.

Thank you

John

**Comment by fade2gray** [comment]
You will find that, nowadays, the number of  'free' sources are very limited and you may benefit by subscribing to a premium provider like Real-Debrid.

**Comment by raffodk** [comment]
Yeah.  Prob go na have to make that move.  Thank you again
