### ISSUE TITLE
Unable to install repo

### ISSUE THREAD

**Issue by mrusli70** [team-crew/team-crew.github.io#65]
I cannot seems to install anything now. It says dependency problems. No python etc etc etc.  Any work arounds???

**Comment by fade2gray** [comment]
Not enough information; OS, Kodi version etc...?

**Comment by mrusli70** [comment]
Even install VPN still cannot install anything. All Kodi are fresh install.

**Comment by mrusli70** [comment]
Install to VMWARE and VirtualBox does not work at all.

**Comment by fade2gray** [comment]
I'm not having any problems installing the repo on Win10/Pi2B/Pi4B.

You are using the correct repo address when adding it to `File manager > Add source`?

https://team-crew.github.io/

**Comment by mrusli70** [comment]
Hi, yeah that's the one that I am using. I do not know whether my isp block it. I have try every OS, Windows, Linux, MacOS nothing seems to work. Even using the VPN. There is no python scripts to load while doing the Install of the repo. That's seems to be weird. I do not know whether the server is down or the ISP block all the server sites.

**Comment by mrusli70** [comment]
See the screenshot there is no script and it cannot install the repo in to kodi. Always gettting script dependancy error.

![Screenshot 2021-09-09 at 11 56 17 AM](https://user-images.githubusercontent.com/64156595/132625396-58c29354-45c0-4b01-822b-f7fb5cef84a7.png)
![Screenshot 2021-09-09 at 12 14 37 PM](https://user-images.githubusercontent.com/64156595/132625428-2505a3ce-0439-4f5a-a403-4ef7a7f78cf4.png)

**Comment by mrusli70** [comment]
This is the error that i get from the log file

![Screenshot 2021-09-09 at 1 06 34 PM](https://user-images.githubusercontent.com/64156595/132626090-19dd1506-e4f7-4e79-b1bc-042a4711d1d4.png)

**Comment by fade2gray** [comment]
I notice `TVAddons` in one of the images - TVA will block TC. You'll need to do a clean install of Kodi without TVA if you want to use TC.

**Comment by mrusli70** [comment]
Hi, I also try on Raspberry Pi 4 with LibreElec Kodi and still I am having problems. I cannot install any repos. As you mentioned earlier. How Do I clean install with TVA??? Because i burn the image it is clean install.

**Comment by fade2gray** [comment]
> How Do I clean install without TVA???

I'm a little confused, from one of the images above it seems that you might be installing TVaddons and then trying to install The Crew - are you using TVAddons?

**Comment by mrusli70** [comment]
Nope! I did not install anything. It was a fresh install. I wonder why I cannot seems to download anything on my Raspberry Pi 4. Long ago I can download and install the repo. But now I can't. It was a freshly install Kodi. But it seems that I cannot install anything even on linux.

**Comment by fade2gray** [comment]
I use LibreElec on my Pi4 as my primary media playback device with no issues - you do have a network connection?

![screenshot00000](https://user-images.githubusercontent.com/1332009/134226738-bfd0295e-f91f-4d74-bfd3-0dd663937cd5.png)

**Comment by mrusli70** [comment]
Here my screenshots, as you can see network is comnected but simehow i cannot install anything on rasoberry pi 4 with libreelec 10.0.0, linux like manjaro, etc. I still getting the same errors!


![20210922_203717](https://user-images.githubusercontent.com/64156595/134347829-0e0b5119-b9e7-4cee-9ffa-f00217e22894.jpg)
![20210922_203550](https://user-images.githubusercontent.com/64156595/134347854-6607cc7d-eaa1-4569-acc8-99ce1fbd77dc.jpg)
![20210922_203505](https://user-images.githubusercontent.com/64156595/134347878-c0cd5fb9-c8ef-491b-b1df-4e5a206976c3.jpg)
![20210922_203121](https://user-images.githubusercontent.com/64156595/134347890-a61ecad0-372e-457a-aee7-4870d515c804.jpg)
![20210922_203027](https://user-images.githubusercontent.com/64156595/134347909-91ebc90b-6549-40a9-b0d1-537ea2de7839.jpg)
![20210922_202932](https://user-images.githubusercontent.com/64156595/134347927-3b362fb9-7622-4e1e-b593-a72c752b2df0.jpg)

**Comment by mrusli70** [comment]
![Uploading 20210922_211058.jpg…]()
![Uploading 20210922_211225.jpg…]()

**Comment by mrusli70** [comment]
![20210922_211058](https://user-images.githubusercontent.com/64156595/134350708-278fb5ad-f35d-4a68-a79c-3584fe014d2d.jpg)
![20210922_211225](https://user-images.githubusercontent.com/64156595/134350745-65dcd54f-95b1-446f-9559-f4e16727cb2f.jpg)

**Comment by mrusli70** [comment]
It could be tge server is blocking the website i cannot seems to install anything at all

**Comment by fade2gray** [comment]
I just created another portable install of Kodi 19 on Win10 and installed The Oath with no problem...

https://user-images.githubusercontent.com/1332009/134387261-8df964a3-2037-4ca9-b3eb-db941b719f7a.mp4

For the dependency issues, you could try downloading them and installing them manually...
http://mirrors.kodi.tv/addons/leia/script.module.six/script.module.six-1.15.0.zip
http://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/script.module.beautifulsoup4-4.9.3.zip

I'm only an end-user myself so my advice is limited and as you are having this problem with multiple repos after a clean install,I don't know what else to suggest.

**Comment by mrusli70** [comment]
Thanks for the infos. I suspected the matter got to do with my ISP network. Will check again and see if it works this time round.

**Comment by zemely** [comment]
Anyone can tell me why Crew repo says installed but is not showing up in KODI repositories?
I had this issue on one NVidia Shield but yesterday it finally updated repo and showed up and works great. But on Another NVidia it still doesn't? Could the repo be offline or something? I checked the url, it's correct.
KODI 19.3, no VPN, no blocking

**Comment by thecrewwh** [comment]
Bitdefender is providing a ton of false positives
