### ISSUE TITLE
Unable to install The Crew or Marauder

### ISSUE THREAD

**Issue by EnderTheDestroyer** [team-crew/team-crew.github.io#66]
I get a message saying the dependency on script.module.myconnpy version 8.0.18 could not be satisfied. Thing is, this is on a Shield Pro 2019 running Kodi Leia, not Matrix. Sucks too, two of my fav addons...any assistance would be GREATLY appreciated!

**Comment by fade2gray** [comment]
http://mirrors.kodi.tv/addons/leia/script.module.myconnpy/script.module.myconnpy-1.1.7.zip

**Comment by EnderTheDestroyer** [comment]
Thanks but I tried that too and I'm still getting the same error message. script.module.myconnpy version 8.0.18 is listed as a dependency when I try installing The Crew or Marauder.

**Comment by fade2gray** [comment]
The Crew, when installed on Leia, will install the v1.1.7 module as a dependency - on Matrix it will install v8.0.18.

It seems, for some reason, when you try to install TC on Leia the process thinks you are trying to install it on a Matrix installation - have you tried to switch between Kodi versions and at some point chosen to keep the data directory? If so, look to see if `.../Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.myconnpy/` directory exists and rename or delete it and try reinstalling TC (you could open the addon.xml file within the directory in an editor and check the version number in it) - if that doesn't work you may have to uninstall Kodi, but don't choose to keep the data/settings directory, and do a clean install.

Hope that makes sense.

**Comment by EnderTheDestroyer** [comment]
Thanks for all your help! I haven't tried switching Kodi versions simply because some of the addons I prefer haven't been ported to Matrix yet. The /Android/data/org.xbmc.kodi/files path has nothing in Files so that's not the problem but I don't mind reinstalling Leia and starting fresh. If that's what I gotta do to get TC and Marauder back then that's what I gotta do! Thanks again, I do believe I owe you a beer.

**Comment by fade2gray** [comment]
II believe the Shield needs to be rooted to gain access to the hidden `.kodi` directory.

**Comment by EnderTheDestroyer** [comment]
I've never done that before but a factory reset should take care of it, wouldn't it?

**Comment by fade2gray** [comment]
I don't have any experience with a Shield, but I think you can gain root access by installing an app - would probably invalidate any warranty you might have on it though.

Just uninstall Kodi but making sure you do not tick the check box to keep your data/settings directory before trying the whole factory reset thing.

Good luck 👍

**Comment by EnderTheDestroyer** [comment]
I can't thank you enough, a fresh reinmstall it is.

**Comment by EnderTheDestroyer** [comment]
Damn, still getting those messages. I've wiped and reinstalled one box 4 times today, either I live with Update Available for metahandler forever or I go without The Crew and Marauder. There doesn't seem to be any way around it, it doesn't matter if I install the zip you provided or not, both addons say they're dependent on scrirpt.module.connpy version 8.0.18. I'm fried, I'm going to chill the rest of tonight. TC and Marauder still work on the Shield so I'll just live with the metahandler Update Available messages.

**Comment by fade2gray** [comment]
You could try asking at the [Addons4Kodi sub-reddit](https://www.reddit.com/r/Addons4Kodi/) but you might then be further redirected to `The Crew Community` using [Telegram Messenger](https://telegram.org/).

**Comment by EnderTheDestroyer** [comment]
Already opened a thread there yesterday, no help so far. I'm not on telegram, kind of surprised I'm the only one with this issue. I decided to move to Matrix, just finished installing all the Matrix addons I like.
