### ISSUE TITLE
The Crew Repo, immediately goes to to disabled state

### ISSUE THREAD

**Issue by sammydc77** [team-crew/team-crew.github.io#7]
This morning, after Indigo [plugin.program.indigo v4.0.18 installed] was updated [It has not worked for about a month], I tried using "The Crew," on Kodi 18.6, it failed with a "Check the Log."  I found the following, in the Log:

2020-04-24 07:42:47.444 T:10202   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named resources.lib.modules
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.thecrew/thecrew.py", line 29, in <module>
                                                from resources.lib.modules import control, log_utils
                                            ImportError: No module named resources.lib.modules
                                            -->End of Python script error report<--
2020-04-24 07:42:47.464 T:10201   ERROR: GetDirectory - Error getting plugin://plugin.video.thecrew/
2020-04-24 07:42:47.519 T:9701   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.thecrew/) failed

I got a New Repo [v3.0 via Github], it installed fine, but did not fix the issue.  I Searched {crew], from within Kodi and found all of you component.  The Crew Repo, had an [X] before it, I enabled the repo, but it immediately returned the [X], disabled.  It will not stay enabled.

Is this a one off, or is there now an Issue?

I am running on a Google Pixelbook 8Gb/256Gb:

2020-04-24 07:39:13.476 T:9701  NOTICE: -----------------------------------------------------------------------
2020-04-24 07:39:13.477 T:9701  NOTICE: Starting Kodi (18.6 Git:20200229-8e967df921). Platform: Android ARM 32-bit
2020-04-24 07:39:13.477 T:9701  NOTICE: Using Release Kodi x32 build
2020-04-24 07:39:13.478 T:9701  NOTICE: Kodi compiled 2020-02-29 by Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) for Android ARM 32-bit API level 21 (API level 21)
2020-04-24 07:39:13.478 T:9701  NOTICE: Running on Google Google Pixelbook with Android 9.0.0 API level 28, kernel: Linux ARM 32-bit version 4.4.211-17202-g02e1f4749ec9
2020-04-24 07:39:13.479 T:9701  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2020-04-24 07:39:13.479 T:9701  NOTICE: Host CPU: ARMv8 processor rev 1 (aarch64), 4 cores available
2020-04-24 07:39:13.480 T:9701  NOTICE: Product: eve, Device: eve_cheets, Board: eve - Manufacturer: Google, Brand: google, Model: Google Pixelbook, Hardware: cheets
2020-04-24 07:39:13.481 T:9701  NOTICE: External storage path = /storage/emulated/0; status = ok
2020-04-24 07:39:13.482 T:9701  NOTICE: ARM Features: Neon enabled
2020-04-24 07:39:13.482 T:9701  NOTICE: special://xbmc/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
2020-04-24 07:39:13.482 T:9701  NOTICE: special://xbmcbin/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
2020-04-24 07:39:13.483 T:9701  NOTICE: special://xbmcbinaddons/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets/addons
2020-04-24 07:39:13.483 T:9701  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
2020-04-24 07:39:13.483 T:9701  NOTICE: special://envhome/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files
2020-04-24 07:39:13.484 T:9701  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
2020-04-24 07:39:13.484 T:9701  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
2020-04-24 07:39:13.484 T:9701  NOTICE: special://logpath/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
2020-04-24 07:39:13.485 T:9701  NOTICE: The executable running is: /data/app/org.xbmc.kodi-90qSGQQFVu6sDVxe5uTIQg==/lib/arm/libkodi.so
2020-04-24 07:39:13.487 T:9701  NOTICE: Local hostname: 100.115.92.10
2020-04-24 07:39:13.488 T:9701  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

This was unusual, so I thought I would ask.  Also, I want to say Great Job, with all that you guys do.

Thanx!

**Comment by eeden003** [comment]
same problem here ! After installing updates fro THE CREW, the REPOhas an X before it AND you haveto search to find it, it seems GONE.  The addon is also GONE !

**Comment by drinfernoo** [comment]
I was unable to replicate this in my 18.6 test install. I was able to install the repo, and add-ons from it, succesfully.

**Comment by sammydc77** [comment]
Okay...  I will accept this as a One-Off, and wait for the next update on
the Repo.

**Comment by eeden003** [comment]
There are more users with NO REPO and NO THE CREW on the user groups on Facebook,so it is NOT a "one-off"  Maybe hidden software in the REPO from THE CREW trying to DISABLE software from TVADDONS ? Some developers still have a grudge ?!

**Comment by sammydc77** [comment]
This did happen immediately after Indigo updated and installed again [works
once then fails, usually disappears after a couple of Kodi restarts], it
has tried to install over the last month or so and failed each time.  I
even had another install attempt the same day, also with the same effect.

I have reviewed the file [thecrew.py, line 29], as the Log indicates, it
does reference [resources.lib.modules], which I have not been able to
locate.  I have explored all copies of my Backups, over the last ten day,
and have found the [thecrey.py] file the same, so I can not locate what is
causing this.

We need to have members of The Crew explore, this is now beyond me.

Time will tell...

**Comment by sammydc77** [comment]
I just had a thought, and experimented a little...  Indigo had popped-up at least four time today, this typically happens when it updates, but it is still at v4.0.18.  So, I went to Addons and searched for Indigo, which I disabled [it now has an "X"].  I then searched for crew, the Repo still had and "X," so I tried to enable it, which held this time with a check mark Proceeding it [enabled status].  I went to [Install from Repo], and The Crew Repo was present, with all options.  I went to Video add-ons, selected [The Crew v0.0.76, which is still indicating active], and updated it, then I opened it, everything appears to work properly again.

Ideally, I would like to uninstall Indigo...  I do not see its purpose, nor function.  I know it can not be uninstalled [to many dependants], but the disabling worked, for me.  Why, this worked is still a question I may never get an answer to.

Just thought I would share this.

**Comment by sammydc77** [comment]
I have just received the latest update from The Crew, Video v0.0.77, plus some other components, so all is still working great.
I do not want to undo anything I have done [by testing again], to get to this point [with The Crew Video v0.0.76a], so I will presume this has become a mute issue.

Thank to The Crew!

**Comment by ts2art** [comment]
Same issue here.... The crew addon just disappeared!! I just tried to reinstall, still get the x when trying to Enable!

**Comment by drinfernoo** [comment]
Uninstall Indigo, and you guys will all be fine...

**Comment by sammydc77** [comment]
Indigo has a lot of dependents, easier to just disable.

**Comment by ts2art** [comment]
I tried to disable... Wouldnt have it so I unistalled ALL addons dependent
on that shit!! Worked so far!! Thank you

**Comment by sammydc77** [comment]
I congratulate you on sticking with it.  I am glad it worked, for you.

**Comment by bob49b** [comment]
Ditto for me.  Had to uninstall Indigo.   Initially Indigo wouldn't uninstall so I downgraded the version and Indigo uninstalled.

**Comment by ts2art** [comment]
Thank you...... I always try everything I can think of BEFORE having to
bother any of you coders!!! I appreciate all your work.... Believe me YOU
are APPRECIATED!!

**Comment by sammydc77** [comment]
Try this first:

Go to Add-ons
Select Search
Search for Indigo
You will have to right-click or equivalent, any of the instances of Indigo
You will see an option [in the content menu] to disable
Select disable
You should see an "X" preceding all instances of Indigo

A t this point:

Go back to Search
Search for "crew"
Select "The Crew Repo," it likely still has an "X" proceeding it.
You will have to right-click or equivalent,
You will see an option [in the content menu] to enable.
Select "Enable"
You should see a check-mark, proceeding "The Crew Repo."

I learned a little known option, which is useful:

From the Add-on Menu [My Add-ons/ Recently Updated/ Install from
Repository...]
Hit the "Left-Arrow," on your Keyboard
You should see "Check for Updates"
Select it, this searches for Updates for everything, immediately.

Sometimes, you will just get a "Blink," which means "nothing new to
update,' otherwise you will see "downloading update."  I typically do this
daily, it just eliminates the wait for something to be pushed.

The Repo and Video, should function now, without future issues.

I hope this all makes sense...
I just found that I did not want to uninstall all the Indigo Dependents.
This worked fine.

Good Luck!

**Comment by sammydc77** [comment]
I am not associated with these great guys [The Crew}.  I am just a User, like you, except I also have 25+ years building and troubleshooting Servers and Networks across the country, now retired.  So, I look at issues differently, from the norm.

**Comment by sammydc77** [comment]
Indigo v4.0.18, just reinstalled and disable The Crew Repo again.  

I just disabled it and went to "Install from zip" to get [The Crew Repo v0.3.0], which has the check-mark proceeding it.  Also, [The Crew Video v0.0.78] is visible and functioning again.

I hope this help, and wishfully this will all go away soon.

**Comment by sammydc77** [comment]
Is anyone a Telegram User?  If so, can you please contact someone, who is part of The Crew.  In The Crew Video App, via Tools / Information, they list all of their Telegram contact information.

I do not think any of them are aware of this Issue.

Thanx!

**Comment by fade2gray** [comment]
I learnt a while ago that 'TV Addons' + 'Indigo' + 'other addons' = 'problems somewhere along the line'.

A clean install of 'Kodi' + 'The Crew' = 'no problems since'.

Just my 5 eggs worth ;)

**Comment by thecrewwh** [comment]
We are well aware of it tva has blocked us install fuck indigo from our repo it will fix your issue and stay away from indigo there is no need for anything from tva

**Comment by sammydc77** [comment]
I have been reluctant to install fuck indigo, but now I am clear as to its
function.

I really appreciate all that you guys do so well.

Thanx!

**Comment by p060477** [comment]
hi..i've the same problem..but unable to solve..:
the crew repo has an -x- and i'm not able to have it workin..and i'm not able to disintall but also to disabilitate indigo cause i have always a pop up: url resolver depends on indigo you cannot disinstall or disabilitate it"
how can i solve this nightmare..??
pls help my cause i'm getting crazy..
thxs in adv
cheers

**Comment by sammydc77** [comment]
This had been closed by [The Crew - April 30th].  I would try contacting
them, via Telegram [as they recommend in the App], otherwise you can open a
New Issue [referencing this one].  The main thing to do is [disable] Indigo
first, then install [fuckindigo].  You can review the last part of the
Issue, for some ideas.

Sorry, but there is nothing more I can add.  Please, read through [the
Issue], particularly near the end.  I have not had any issues since.

**Comment by p060477** [comment]
the tricks showed here really do not work...
:(

**Comment by p060477** [comment]
" I have not had any issues since."...
..now you have mine...

**Comment by sammydc77** [comment]
I have sent a message to [thecrewwh], that this issue is alive again
[please review the bottom of Issue #8], it would be best to open/create a
New Issue, otherwise it will not be notice be The Crew [since Issues #7 and
#8 have been closed by The Crew].  I am not part of The Crew, and only
offered what help I could, at the time.  This issue went away, after
[fuckindigo v0.0.2] came out.

Good Luck

**Comment by drinfernoo** [comment]
This isn't an issue with THE CREW or their repository. Other add-ons take action to disable them, so removing those add-ons is the answer.

**Comment by p060477** [comment]
..there is no way to remove url resolver..or you won't' be able to use the majority of add ons...

**Comment by bob49b** [comment]
The only way I've been able to do it is:
- Install Kodi from scratch
- Do not install apps like Exodus which have url resolver as a dependency
- Once url resolver is installed Indigo gets installed and you're screwed
- If you want Exodus get the Redux version
- Install Crew and your other desired addons being careful to avoid any
addon using url resolver.

Bob

**Comment by p060477** [comment]
this seems a hands up to indigo and its very unfair behaviour...
it should be much more useful and better to try to -unistall- indigo
IMHO

**Comment by drinfernoo** [comment]
If you are going to use add-ons that use URLResolver, just don't install repos that include Indigo, then 🤷🏽‍♀️

THE CREW *by itself* works just fine, and doesn't disable *itself*, obviously.

The reason you people are having trouble is because you're using repositories that deliver malicious add-ons, and settings that allow those repositories to install whatever they want on your system.

**Comment by bob49b** [comment]
Here's the proof:
https://koditips.com/tvaddons-indigo-installed/

Other add-ons use the app resolveurl to accomplish the functionality of
urlresolver and avoid the baggage that comes with urlresolver.

**Comment by p060477** [comment]
> 
> 
> If you are going to use add-ons that use URLResolver, just don't install repos that include Indigo, then 🤷🏽‍♀️
> 
> THE CREW _by itself_ works just fine, and doesn't disable _itself_, obviously.
> 
> The reason you people are having trouble is because you're using repositories that deliver malicious add-ons, and settings that allow those repositories to install whatever they want on your system.

..no...the problem is Indigo..and the fact tthat there is no way to unistall or disable it..
if you want yr crew add on works you ought to think about a solution...
otherwise so many people like me won't be able to use the crew
hope this interest you
think it should...

**Comment by sammydc77** [comment]
To p060477:

Please take a breath and think before you try to denigrate this great group
of people, at the Crew.  They have spent hundreds of hours coding, to
provide you this extremely well-thought-out and functional App, for free.
You need to take a moment and read the Link provided by bob49b, it is a
very simple sequence to follow to fix this issue.  The Crew, have also
provided the [Fuck Indigo] App, available via their Repo, under Programs,
which is now in its second revision, since tvaddons found a way around the
first.  I went through this, back in the end of April/2020 and have not
seen this issue arise again.  By the way this is not the first time that
tvaddons has done something like this [the bob49b Link will give you
details].  I appreciate your time trying to fix this on your own, but you
will find there are many people who care...  Just my thoughts.

**Comment by p060477** [comment]
..maybe you have to take a breathe before comment my post..if you'll do you realize that 
because I LOVE THE ADD ON: the Crew
but now for me..and not only..there is NO WAY TO USE IT....
and all the fixes provided here DO NOT WORK...
all
the one posted
and the one linked
so my is really not an order
is a PRAYER
give us the way to unistall Indigo
thxs to YOU ALL

**Comment by sammydc77** [comment]
It was given to you already, if you would only read the Link in the post
above yours [bob49b]:

https://koditips.com/tvaddons-indigo-installed/

**Comment by p060477** [comment]
..oh if you only read mine...:
i re-post here hoping you read before replying..:
"and all the fixes provided here DO NOT WORK...
all
the one posted
and the one ->LINKED<- "
..pls read -before- replying...
so much thxs indeed to you
ALL

**Comment by drinfernoo** [comment]
Do you need a video to prove that THE CREW by itself works just fine? 🤦🏽‍♂️ I have no affiliation with the add-on, but this is a pointless discussion about an issue that isn't valid.

**Comment by p060477** [comment]
maybe you do not have understood ANY of my posts..:
SURELY the Crew works fine....- BY ITSELF-..
but have you understood that the problem is when you already have  -also- INDIGO..??...
if you have it and you are not lucky to solve with the fixes given here
the Crew really DO NOT WORK AT ALL
so pls BEFORE replying READ CAREFULLY
thxs so much in advance
to you ALL

**Comment by p060477** [comment]
the goal should be to UNISTALL Indigo
but i re-underline -for the hard to understand-
that is some cases, that are not really few and are increasing
the fixes given here do not work
hoping to have be much more clear
i PRAY the add on dev to try and find a method to -unistall- indigo
also for the ones that are not able to with the fixes given here up to now
this is not an ORDER
is only a PRAYER
thxs to you
ALL

**Comment by sammydc77** [comment]
This Issue #7 was closed at the beginning of May/2020.  This has been re-opened in Issue #18 [by p06477],   The Crew, will not look at Closed Issues.  You should consider writing your comments, in the Open Issue #18, so it will get The Crew's attention.  I contacted thecrewwh, and informed them that this Issue has returned, with people commenting here [closed - Issue #7], it got the attention of drinfernoo, which is all I can do. If you want to pursue this, please use Issue #18.

Good Luck

**Comment by ctgocart** [comment]
Hello!

I have a problem with LiveStreamPor Addon giving an error 404 and CREW doesn't work anymore, can you tell me how to fix it please??

**Comment by jimchest** [comment]
my fresh install of windows 10 had same issue.  the windows antivirues views the python code as a virus.  "Error Contents: [Errno 22] Invalid argument: 'C:\\Users\\jimchest\\AppData\\Roaming\\Kodi\\addons\\plugin.program.thecrewiz\\uservar.py".... Once I turned off ALL antivirus and Firewall.  everything installed fine.  took me awhil to figure that out.
