### ISSUE TITLE
Lol section 

### ISSUE THREAD

**Issue by zZC0R3YZz** [team-crew/team-crew.github.io#87]
Hi there been using your addon for a while now and love it thanks for all the hard work and effort. 
The past few days i have been running into this certain issue when you enter lol to unlock the section it shows up on the front page just fine. 
But when you click to go into that section the loading circle comes up and then disapears fast and you just stay on the front page. 
Have tried uninstalling the addon and re installing it.
I am using RD and running Kodi version 19.3 and addon version 1.1.5
Everything else works great and exactly like it should so i thank you for the hard work and great addon 
Any help on the issue will be greatly appricated though thank you

**Comment by spud09** [comment]
Same issue on 19.3, version 1.1.5

**Comment by TrillaG** [comment]
Same problem. Has happened to me before and it fixed itself in time, but then broke again. I don't think this addon has support anymore so I doubt it will get fixed.

**Comment by thecrewwh** [comment]
It opens for me just fine make sure you are on kodi 19
