### ISSUE TITLE
Trakt Progress takes a long time and sends too many requests

### ISSUE THREAD

**Issue by alfadog67** [team-crew/team-crew.github.io#89]
I've noticed that when a show with many episodes is loaded in Trakt Progress, it takes an inordinate amount of time to load.
There seem to be many, many more requests sent to Trakt API as compared to Exodus Redux.
One workaround I've been using is to change the get() function in episodes.py (line 589) to [season] instead of [-1]. 
That returns the unwatched episodes for only the current season instead of all unwatched episodes, so potentially saves lots of time, but there are still many requests sent per episode.

**Comment by alfadog67** [comment]
I'm a noob to Github, so not sure how I closed this issue 29 seconds after I opened it - Sorry!

**Comment by fade2gray** [comment]
The Crew devs rarely respond in here, it would be best to contact 'Team Crew' using [Telegram Messenger](https://telegram.org/).
