### ISSUE TITLE
Sports leagues

### ISSUE THREAD

**Issue by ProjectB2** [team-crew/team-crew.github.io#90]
None of the sports leagues are loading

**Comment by Sobersally** [comment]
I second that!

**Comment by viachy** [comment]
It`s 5AM where I live and just wanted to turn on the MEM-GSW game, and I thought my tv box is playing jokes with me... tried everything I could think of.. rebooted the router, reinstalled the addon, but when I go to the sports section it just reloads the screen.... I hope the guys can fix it quickly (not for this game but for the next days...) thanks for your work team.

**Comment by fade2gray** [comment]
The Crew devs rarely respond in here, it would be best to contact 'Team Crew' using [Telegram Messenger](https://telegram.org/).
