### ISSUE TITLE
IPTV not opening 

### ISSUE THREAD

**Issue by ieswideopen** [team-crew/team-crew.github.io#91]
The iptv section won't load anymore

**Comment by ieswideopen** [comment]
Ignore please. It loaded today 🤷

**Comment by joe71101** [comment]
Mine is also not opening.  Did you do anything special to get yours to open?

**Comment by Zippy457** [comment]
Not working today (again!).
Was working just fine for the past couple of weeks, since I uninstalled and re-installed the add-on.
Today, that fix doesn't seem to help.

**Comment by SpaceIgniter** [comment]
Same issue here. It's been about 2 weeks where the IPTV section is not working.
I've tested with multiple devices and with different VPNs and ISPs. Makes no difference.
