### ISSUE TITLE
real debrid requires re-auth every start of the crew

### ISSUE THREAD

**Issue by shanness** [team-crew/team-crew.github.io#93]
It works when I auth it, but a day later, fails (just skips all RD links) until I re-auth it.

Multiple people (me and another) reporting it here.

https://www.reddit.com/r/Addons4Kodi/comments/prg3bp/the_crew_on_kodi_19_setup_real_debrid/ictaipx/?context=3

**Comment by fade2gray** [comment]
I notice the other user reported their issue on the SubReddit 24 days ago, presumably they resolved it.

Have you recently updated The Crew addon and module? I'm currently using addon/v1.1.6 and v1.1.6e/module, without any RealDebrid problems, but I notice addon/v1.1.6b and module/v1.16f are waiting to be installed - I'll defer for now.

**Comment by EvilCaptKirk** [comment]
I also have experienced this issue on both Linux and Windows installs of the 19.x branch of Kodi, The Crew v1.1.6b, ResolveURL 5.1.64.  I've tried the fix suggested here (editing realdebrid.py and re-authorizing https://www.reddit.com/r/Addons4Kodi/comments/v7zzer/reauthorize_realdebrid_every_day/) but the issue persists. Appreciate any suggestions on further troubleshooting steps.

**Comment by EvilCaptKirk** [comment]
Update: I'm an idiot. An outdated version of ResolveURL from a dead repo was the cause of this problem. The Crew repo had the current version - I had not originally installed it from there, so it had stopped updating. Manual updated to the latest, problem solved. :)

**Comment by shanness** [comment]
> Update: I'm an idiot. An outdated version of ResolveURL from a dead repo was the cause of this problem. The Crew repo had the current version - I had not originally installed it from there, so it had stopped updating. Manual updated to the latest, problem solved. :)

Ahh! That makes sense.  Sorry if this is a bit n00by, but how to manually update it?  I suppose I could remove all the old pre "crew" repos.  Seems annoying that old repos are causing it to stick on an old version?  No isolation (python venv?) for apps?

**Comment by fade2gray** [comment]
https://user-images.githubusercontent.com/1332009/205037691-6f77ec4a-9374-4b20-9f8c-e1225304220e.mp4

**Comment by EvilCaptKirk** [comment]
> > Update: I'm an idiot. An outdated version of ResolveURL from a dead repo was the cause of this problem. The Crew repo had the current version - I had not originally installed it from there, so it had stopped updating. Manual updated to the latest, problem solved. :)
> 
> Ahh! That makes sense. Sorry if this is a bit n00by, but how to manually update it? I suppose I could remove all the old pre "crew" repos. Seems annoying that old repos are causing it to stick on an old version? No isolation (python venv?) for apps?

@fade2gray's video shows the steps I took. :)
