### ISSUE TITLE
Pop up messages do not go away!

### ISSUE THREAD

**Issue by markosjal** [team-crew/team-crew.github.io#94]
This addon is hammering my Kodi installs with messages that do not go away.  I have to reboot or restart Kodi to clear them. Please change addon so these messages can be disabled! I do not want to see every time something updates like this it should do so silently in the background. They should be disabled by default too!
![screenshot00030](https://user-images.githubusercontent.com/281916/179117599-7513103b-f256-4ebb-bc86-a7308096fcdb.png)
![screenshot00026](https://user-images.githubusercontent.com/281916/179117601-03ab72ea-4b19-49bf-b929-b392b55ffea3.png)

Running 
Libreelec 10.02, kodi 19.4 
Windows 10 Kodi 19.4

**Comment by thecrewwh** [comment]
Turn off trakt sync in settings
