### ISSUE TITLE
Resume Playback Feature Not Working

### ISSUE THREAD

**Issue by Modifyinc** [team-crew/team-crew.github.io#95]
Is there a trick to getting the Resume Playback feature to actually work? I've installed The-Crew on multiple Fire Sticks and not one of them will resume playback if I stop the movie/show and come back later to view it. I have enabled the Resume Playback option but it never works. With other add-ons, I would usually get an option to start from beginning or to continue from where I left off.

Is this a bug? Is there a way to make it work?

**Comment by suzie59** [comment]
I'm getting the samething.. Playback failed.. I love Investigation Discovery and AE can't get either of those?

**Comment by apg31** [comment]
Resume playback works in 18 .9 but not in 19.4.
No error message though just always starts from beginning.
I also tried using it with Trakt, same thing.
other addons work fine so I do not think it is anything I have set wrong.
