### ISSUE TITLE
Cast photographs 

### ISSUE THREAD

**Issue by zdcyclops** [team-crew/team-crew.github.io#97]
The photos of cast members do not download. Only the names appear.
My setup :
Running on Kodi 19.4 On

OS Name	Microsoft Windows 10 Home
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-6PHFQ7Q
System Manufacturer	HP
System Model	510-p030
System Type	x64-based PC
System SKU	V8P12AAR#ABA
Processor	Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz, 2808 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	AMI F.42, 9/23/2016
SMBIOS Version	2.8
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	HP
BaseBoard Product	81B4
BaseBoard Version	00
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.1806"
User Name	DESKTOP-6PHFQ7Q\Me
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	12.0 GB
Total Physical Memory	11.8 GB
Available Physical Memory	7.22 GB
Total Virtual Memory	13.6 GB
Available Virtual Memory	8.64 GB
Page File Space	1.81 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

Copy and paste from the addon .xml

<?xml version="1.0" encoding="UTF-8"?>
<addon id="repository.thecrew" name="[COLOR orchid]THE CREW REPO[/COLOR]" provider-name="The Crew" version="0.3.4">
	<extension point="xbmc.addon.repository" name="The Crew" >
			<dir minversion="16.0.0" maxversion="18.9.9">

**Comment by fade2gray** [comment]
See this for support - https://github.com/team-crew/team-crew.github.io/issues/108#issue-1427802412

**Comment by zdcyclops** [comment]
Not interested in installing an app to tell someone their addon needs work,
I will just use an addon that has no such problem.

**Comment by thecrewwh** [comment]
Go for it lol
