### ISSUE TITLE
Adding providers

### ISSUE THREAD

**Issue by thenextgod** [team-crew/team-crew.github.io#99]
Is there any way to add(or edit existing) new providers? (similar to how you can do it in elementum with override file?)

**Comment by fade2gray** [comment]
Well, you can enable/disable providers via the settings interface, but to actually add new, or edit existing, I think you'd need to edit the `C:\Users\<UserName>\AppData\Roaming\Kodi\addons\plugin.video.thecrew\resources\settings.xml` file.

Other than that, you can try asking `Team-Crew` on [Telegram Messenger](https://telegram.org).

**Comment by thecrewwh** [comment]
Yes you could add them if you wanted you need to wirte them and add them
